### ISSUE TITLE
0.5.2: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by maxhoffmann** [rollbar/node_rollbar#42]
We got this error on production, when someone tried accessing a page that didn’t exist multiple times. It currently crashes the server.

```
runMicrotasksCallback (node.js:337:7)
process._tickCallback (node.js:355:11)
/app/node_modules/rollbar/lib/notifier.js:270
addReqDataFn(baseData, item.request);
RangeError: Maximum call stack size exceeded at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) at addRequestData (/app/node_modules/rollbar/lib/notifier.js:270:7) Exception
```

**Comment by brianr** [comment]
Thanks for the report, @maxhoffmann . Is there a framework you're using, e.g. express?

**Comment by maxhoffmann** [comment]
Yes, using we are express.

**Comment by coryvirok** [comment]
Hey Max. I think this is fixed in v0.5.3. Can you verify? https://github.com/rollbar/node_rollbar/commit/9be765d58ace0bc80ea8467c6fcc895e254bd4b9

**Comment by maxhoffmann** [comment]
Will update and test again.

**Comment by maxhoffmann** [comment]
I can’t reproduce it after updating. Seems that it’s okay. I’ll let you know if it occurs again. Thanks for the quick fix! :+1:

**Comment by coryvirok** [comment]
Thanks Max!
