### ISSUE TITLE
Express 4: app.use(rollbarMiddleware) is not recognized or notified

### ISSUE THREAD

**Issue by InstanceOfMichael** [rollbar/node_rollbar#66]
```
  "dependencies": {
    "body-parser": "~1.13.3",
    "dotenv": "~1.2.0",
    "es6-promise": "~3.0.2",
    "express": "^4.13.3",
    "request-promise": "~0.4.3",
    "rollbar": "^0.5.11",
  }
```
```
InstanceOfMichael@sg-u15-vm:~/www$ npm -v
3.5.2
InstanceOfMichael@sg-u15-vm:~/www$ node -v
v0.12.9
```

Failing code snippet

```
require('dotenv').load();

process.env.APP_PORT = process.env.APP_PORT || 3020;

var Promise = require("es6-promise").Promise;
var express = require('express');
var app = express();

var rp = require('request-promise');
var rollbar = require("rollbar");
rollbar.init(process.env.ROLLBAR_ACCESS_TOKEN);
rollbar.reportMessage("Hello world!");

var rollbarMiddleware = rollbar.errorHandler(process.env.ROLLBAR_ACCESS_TOKEN, {environment: app.settings.env});
// var rollbarMiddleware = rollbar.errorHandler({environment: app.settings.env});

// app.use(rollbarMiddleware);

var server = app.listen(process.env.APP_PORT, function() {
  console.log('Listing on port: ' + process.env.APP_PORT);

  //request, but with promises
  setTimeout(function(){
      rp('http://localhost:'+process.env.APP_PORT+'/rollbar/test');
  },250);
});

app.get('/rollbar/test',
    function(req,res,next)
    {
        console.log('http request received!');
        next();
    },
    rollbarMiddleware,
    function(req,res)
    {
        throw new Error('rollbar test');
    }
);
```
```
InstanceOfMichael@sg-u15-vm:~/www$ node rollbartest.js
Listing on port: 3010
http request received!
Error: rollbar test
    at /home/InstanceOfMichael/www/rollbartest.js:36:15
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/InstanceOfMichael/www/node_modules/express/lib/router/route.js:131:13)
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:91:12)
    at next (/home/InstanceOfMichael/www/node_modules/express/lib/router/route.js:131:13)
    at /home/InstanceOfMichael/www/rollbartest.js:31:9
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/InstanceOfMichael/www/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/InstanceOfMichael/www/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:95:5)
    at /home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:330:12)
    at next (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/InstanceOfMichael/www/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:312:13)
    at /home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:330:12)

    at next (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:271:10)
    at query (/home/InstanceOfMichael/www/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/home/InstanceOfMichael/www/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/InstanceOfMichael/www/node_modules/express/lib/router/index.js:312:13)
[Rollbar] Successful api response
```

![rollbarexpressnotworking](https://cloud.githubusercontent.com/assets/4094542/12130365/6ef0309c-b3cf-11e5-8339-ef3f6ceaac99.PNG)

 - ``rollbar.reportMessage("Hello world!");`` maps to ``[Rollbar] Successful api response`` and is sent to my dashboard
 - ``Error('rollbar test');`` is not sent to my rollbar dashboard

**Comment by coryvirok** [comment]
Is the process exiting as soon as the `throw new Error('rollbar test')` is bubbled up to express? If so, the process may be exiting before Rollbar has a chance to send the error. 

Can you add this to your `setTimeout()`?

```js
  //request, but with promises
  setTimeout(function(){
      rp('http://localhost:'+process.env.APP_PORT+'/rollbar/test');

      // Wait 5 seconds before allowing the process to exit
      console.log('Waiting for 5 seconds before exiting');
      setTimeout(function() {
          console.log('Exiting');
      }, 5000);
  },250);
```

Does the middleware work if you use `app.use()`?

Thanks in advance.

**Comment by InstanceOfMichael** [comment]
I think this was the core of the issue, the ``app.use`` function call has to be made after all normal middleware and routes are define

```
// Express version 4
// @link http://expressjs.com/en/guide/error-handling.html
// You define error-handling middleware last, after other app.use() and routes calls
app.use(rollbar.errorHandler({environment: app.settings.env}));
```

**Comment by coryvirok** [comment]
Ah. Glad you figured it out.

**Comment by peeinears** [comment]
Please put this in the documentation!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by InstanceOfMichael** [comment]
:+1:
