### ISSUE TITLE
Errors when Install using the node package manager

### ISSUE THREAD

**Issue by albertolive** [rollbar/node_rollbar#84]
Hi, I have installed this tool (I'm using webpack) and I'm having this errors:

```javascript
./~/rollbar/package.json
Module parse failed: /Dashboard/node_modules/rollbar/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "rollbar",
 @ ./~/rollbar/lib/notifier.js 14:18-44


./~/rollbar/lib/parser.js
Module not found: Error: Cannot resolve module 'fs' in /Dashboard/node_modules/rollbar/lib
resolve module fs in /Dashboard/node_modules/rollbar/lib
  looking for modules in /Dashboard/node_modules/rollbar/node_modules
    resolve 'file' fs in /Dashboard/node_modules/rollbar/node_modules
      resolve file
        /Dashboard/node_modules/rollbar/node_modules/fs doesn't exist
        /Dashboard/node_modules/rollbar/node_modules/fs.js doesn't exist
        /Dashboard/node_modules/rollbar/node_modules/fs.jsx doesn't exist
    /Dashboard/node_modules/rollbar/node_modules/fs doesn't exist (module as directory)
  looking for modules in /Dashboard/node_modules
    resolve 'file' fs in /Dashboard/node_modules
      resolve file
        /Dashboard/node_modules/fs doesn't exist
        /Dashboard/node_modules/fs.js doesn't exist
        /Dashboard/node_modules/fs.jsx doesn't exist
    /Dashboard/node_modules/fs doesn't exist (module as directory)
    resolve 'bower component' fs manifest files using [bower.json]
      resolve file
        /Dashboard/node_modules/rollbar/lib/bower_components/fs/bower.json doesn't exists
        /Dashboard/node_modules/rollbar/bower_components/fs/bower.json doesn't exists
        /Dashboard/node_modules/bower_components/fs/bower.json doesn't exists
        /Dashboard/bower_components/fs/bower.json doesn't exists
        /bower_components/fs/bower.json doesn't exists
        /Users/albertolive/bower_components/fs/bower.json doesn't exists
        /Users/bower_components/fs/bower.json doesn't exists
        /bower_components/fs/bower.json doesn't exists
[/Dashboard/node_modules/rollbar/node_modules/fs]
[/Dashboard/node_modules/rollbar/node_modules/fs.js]
[/Dashboard/node_modules/rollbar/node_modules/fs.jsx]
[/Dashboard/node_modules/rollbar/node_modules/fs]
[/Dashboard/node_modules/fs]
[/Dashboard/node_modules/fs.js]
[/Dashboard/node_modules/fs.jsx]
[/Dashboard/node_modules/fs]
 @ ./~/rollbar/lib/parser.js 7:9-22
```
I tried to fix it but with no luck. Somebody can help me? 

Thanks!

**Comment by coryvirok** [comment]
Looks like your Webpack build is attempting to include `package.json` but doesn't have a loader which understands JSON. You may just be able to add https://github.com/webpack/json-loader and the appropriate Webpack loader config.

The other problem looks like you don't have node_modules in your Webpack resolve path. Try adding something like this to your Webpack config:

```js
resolve: {
    root: __dirname,
    modulesDirectories: ["node_modules"]
  },
```

**Comment by albertolive** [comment]
Ok, thanks!

**Comment by brianr** [comment]
@albertolive Were you able to get this working? I'm going to close this issue, but please reopen if there's still a problem that appears to be with node_rollbar itself.

**Comment by bmueller-sykes** [comment]
I'm having a similar problem with a webpack/React/ES6-based project. In my package.json file, I've got this reference:

`"rollbar": "0.6.2",`

...and the install appears to go properly, but then when I do `npm start`, I get the following error trace in the console (some project-specific details masked):

```
ERROR in ./~/rollbar/lib/parser.js
Module not found: Error: Cannot resolve module 'fs' in [myProjectRoot]node_modules/rollbar/lib
 @ ./~/rollbar/lib/parser.js 7:9-22

ERROR in ./~/rollbar/package.json
Module parse failed: [myProjectRoot]node_modules/rollbar/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.semicolon ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1469:73)
    at Parser.pp.parseExpressionStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1994:8)
    at Parser.pp.parseStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1772:188)
    at Parser.pp.parseBlock ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:2009:21)
    at Parser.pp.parseStatement ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1753:19)
    at Parser.pp.parseTopLevel ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1666:21)
    at Parser.parse ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:1632:17)
    at Object.parse ([myProjectRoot]node_modules/webpack/node_modules/acorn/dist/acorn.js:885:44)
 @ ./~/rollbar/lib/notifier.js 14:18-44
```

here's the (potentially) relevant part of my webpack.config file:

```
    loaders: [
			{
	      test: /\.(js|jsx)$/,
	      loader: 'babel',
	      query: {
		      // https://github.com/babel/babel-loader#options
		      cacheDirectory: true
	      },
	      include: path.join(__dirname, 'src'),
	      exclude: /node_modules/
	    },
	    { test: /\.css$/, loader: 'style-loader!css-loader' },
	    { test: /\.woff|.ttf|.eot|.woff2$/, loader: `file-loader` },
	    { test: /\.(png|jpe?g|gif|svg)$/, loader: `url-loader?limit=8192` },
		]
	}	
```

I do not explicitly have a loader that parses JSON, but my webpack project has about 30 other NPM packages, and it builds just fine. Is there something unique about Rollbar that it needs a special loader?
