### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by maximilianschmitt** [rollbar/node_rollbar#88]
There is a [merged pull request for a similar issue](https://github.com/rollbar/node_rollbar/pull/19) but it seems like errors with circular structure cannot be reported and crash the process.

``` javascript
'use strict'

const rollbar = require('rollbar')

rollbar.init('ROLLBAR_ACCESS_TOKEN', {
  environment: 'development'
})

const circularError = { error: {} }
circularError.error.hello = circularError.error

rollbar.handleError(circularError, undefined, function (rollbarErr) {
  if (rollbarErr) {
    console.error('Could not report error to Rollbar')
    console.trace(((rollbarErr && rollbarErr.stack) || rollbarErr) + '\n')
  } else {
    console.log('Finished reporting error to Rollbar')
  }
})
```

```
~ $ node rollbar-test.js
~/node_modules/rollbar/lib/notifier.js:464
  return exports.reportMessage(JSON.stringify(err), 'error', req, callback);
                                    ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Object.exports.handleError (~/node_modules/rollbar/lib/notifier.js:464:37)
    at Object.<anonymous> (~/rollbar-test.js:12:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

It seems like the rollbar-module is missing to properly handle the `TypeError`. If it will not convert circular structures to JSON gracefully, shouldn't it at least pass the `TypeError` to the error-first callback?

**Comment by rokob** [comment]
@lehresman you were right, that just needed to get merged. I updated that PR a little bit to match the style we already have in api.js for consistency and merged it.
